%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.10.5

-ifndef(connection_app_pb).
-define(connection_app_pb, true).

-define(connection_app_pb_gpb_version, "4.10.5").

-ifndef('CONNECTIONPROCESS_PB_H').
-define('CONNECTIONPROCESS_PB_H', true).
-record(connectionprocess,
        {username = <<>>        :: iodata() | undefined, % = 1
         id = 0                 :: integer() | undefined % = 2, 32 bits
        }).
-endif.

-endif.
