%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.17.3

-ifndef(connection_app).
-define(connection_app, true).

-define(connection_app_gpb_version, "4.17.3").

-ifndef('CONNECTIONPROCESS_PB_H').
-define('CONNECTIONPROCESS_PB_H', true).
-record('ConnectionProcess',
        {'Username' = []        :: unicode:chardata() | undefined, % = 1, optional
         'Id' = 0               :: integer() | undefined % = 2, optional, 32 bits
        }).
-endif.

-endif.
